# Generated by Django 3.1.2 on 2020-11-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='ingredients here', help_text='Enter the ingredients', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='steps here', help_text='Detail the cooking steps', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='images\\macncheese.jpg', upload_to='images'),
        ),
    ]
