# Generated by Django 3.1.2 on 2020-11-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201118_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='summary',
            field=models.TextField(default='Enter bio here', help_text='Tell us about yourself!', max_length=1000),
        ),
    ]
