# Generated by Django 3.1.2 on 2020-11-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20201124_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='type_of_food',
        ),
        migrations.AddField(
            model_name='recipe',
            name='type_of_food',
            field=models.CharField(default='other', help_text='Select what kind of dish this is', max_length=500),
        ),
        migrations.AlterField(
            model_name='type_of_food',
            name='name',
            field=models.CharField(help_text='Enter a type of food (e.g. Mexican, Pasta)', max_length=500),
        ),
    ]
