# Generated by Django 3.1.2 on 2020-11-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20201128_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': (('can_update', 'can_delete'),)},
        ),
    ]
