# Generated by Django 3.1.2 on 2020-12-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20201130_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='ingredients here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='steps here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type_of_food',
            field=models.CharField(default='other', max_length=500),
        ),
        migrations.AlterField(
            model_name='type_of_food',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
